services:
  dotabase-web:
    restart: unless-stopped
    container_name: dotabase-web
    build: .
    environment:
      - PORT=3000
      - VPK_DIR=/dotavpk
    volumes:
      - ${VPK_DIR}:/dotavpk
    ports:
      - 3000:3000
    